[versions]
loom = "1.15-SNAPSHOT"

minecraft = "1.21.11"
#yarn = "1.21.11+build.4"
loader = "0.18.6"
fabric_api = "0.141.3+1.21.11"


malilib = "0.27.7"
modmenu = "17.0.0"
fabrishot = "1.16.4"
iris = "1.10.7+1.21.11-fabric"
sodium = "mc1.21.11-0.8.7-fabric"


jgit = "7.3.0.202506031305-r"

# use from iris source
antlr = "4.13.1"
glsl_transformer = "3.0.0-pre3"
jcpp = "1.4.14"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
#yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

malilib = { module = "maven.modrinth:malilib", version.ref = "malilib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabrishot = { module = "maven.modrinth:fabrishot", version.ref = "fabrishot" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

antlr = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
glsl_transformer = { module = "io.github.douira:glsl-transformer", version.ref = "glsl_transformer" }
jcpp = { module = "org.anarres:jcpp", version.ref = "jcpp" }

jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }