[versions]
minecraft = "26.2"
loader = "0.19.3"
loom = "1.17-SNAPSHOT"
fabric_api = "0.156.0+26.2"


malilib = "0.29.3"
#malilib = "26.2-0.29.2"
modmenu = "20.0.1"
fabrishot = "1.17.0"
iris = "1.11.2+26.2-fabric"
sodium = "mc26.2-0.9.1-fabric"
voxy = "0.2.18-beta"


jgit = "7.3.0.202506031305-r"

# use from iris source
antlr = "4.13.1"
glsl_transformer = "3.0.0-pre3"
jcpp = "1.4.14"


[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
#yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

#malilib = { module = "maven.modrinth:malilib", version.ref = "malilib" }
#malilib = { module = "com.github.sakura-ryoko:malilib", version.ref = "malilib" }
malilib = { module = "fi.dy.masa.malilib:malilib-fabric-26.2", version.ref = "malilib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabrishot = { module = "maven.modrinth:fabrishot", version.ref = "fabrishot" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
voxy = { module = "maven.modrinth:voxy", version.ref = "voxy"}

antlr = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
glsl_transformer = { module = "io.github.douira:glsl-transformer", version.ref = "glsl_transformer" }
jcpp = { module = "org.anarres:jcpp", version.ref = "jcpp" }

jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }